services:
  - type: web
    name: noirlol
    runtime: node
    plan: free

    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run render:start

    healthCheckPath: /api/health

    envVars:
      - key: NODE_ENV
        value: production

      - key: DATABASE_URL
        fromDatabase:
          name: noirlol-db
          property: connectionString

      - key: JWT_SECRET
        generateValue: true

      - key: IP_HASH_SECRET
        generateValue: true

      - key: APP_URL
        sync: false

      - key: DISCORD_CLIENT_ID
        sync: false

      - key: DISCORD_CLIENT_SECRET
        sync: false

      - key: S3_ENDPOINT
        sync: false

      - key: S3_REGION
        value: auto

      - key: S3_BUCKET
        sync: false

      - key: S3_ACCESS_KEY_ID
        sync: false

      - key: S3_SECRET_ACCESS_KEY
        sync: false

      - key: S3_PUBLIC_URL
        sync: false

databases:
  - name: noirlol-db
    plan: free
    databaseName: noirlol
    user: noirlol
