'use client';
import { useMemo, useState } from 'react';
import { ExternalLink, LogOut, Plus, Save, Trash2, Upload, ArrowUp, ArrowDown, Copy } from 'lucide-react';
import { useRouter } from 'next/navigation';
const tabs=['Perfil','Medios','Apariencia','Efectos','Enlaces','Widgets','SEO','Aliases','Host','Estadísticas','Avanzado'] as const;
const layouts=['DEFAULT','MODERN','SIMPLISTIC','SLEEK'];
const bgEffects=['none','particles','grid','stars','noise','vignette','scanlines'];
const nameEffects=['none','glow','gradient','pulse','shimmer','outline'];
const cursorEffects=['none','trail','glow','ring'];
const profileAnimations=['none','fade','rise','scale','blur'];
function Field({label,children}:{label:string,children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function Toggle({label,value,onChange}:{label:string,value:boolean,onChange:(v:boolean)=>void}){return <label className="toggle"><span>{label}</span><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/><i/></label>}
export default function DashboardClient({data}:{data:any}){
 const r=useRouter(); const [tab,setTab]=useState<(typeof tabs)[number]>('Perfil'); const [p,setP]=useState<any>(data.profile); const [links,setLinks]=useState<any[]>(data.links||[]); const [aliases,setAliases]=useState<any[]>(data.aliases||[]); const [hosted,setHosted]=useState<any[]>(data.hosted||[]); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState('');
 const widgets=useMemo(()=>Array.isArray(p.widgets)?p.widgets:[],[p.widgets]);
 const typewriterText=useMemo(()=>Array.isArray(p.typewriterTexts)?p.typewriterTexts.join('\n'):'',[p.typewriterTexts]);
 function patch(k:string,v:any){setP((x:any)=>({...x,[k]:v}))}
 async function save(){setBusy(true);setMsg('');const res=await fetch('/api/profile',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(p)});setBusy(false);setMsg(res.ok?'Cambios guardados':'No se pudieron guardar los cambios');}
 async function upload(file:File,target:string){setBusy(true);const f=new FormData();f.append('file',file);const res=await fetch('/api/upload',{method:'POST',body:f});const j=await res.json();setBusy(false);if(res.ok)patch(target,j.url);else setMsg(j.error||'Error al subir');}
 async function addLink(){const label=prompt('Nombre del enlace');const url=prompt('URL completa');if(!label||!url)return;const res=await fetch('/api/links',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({label,url})});const j=await res.json();if(res.ok)setLinks(x=>[...x,j]);else setMsg(j.error||'No se pudo añadir');}
 async function saveLinks(next=links){setLinks(next);await fetch('/api/links',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({items:next})});}
 async function delLink(id:string){await fetch('/api/links',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({id})});setLinks(x=>x.filter(v=>v.id!==id));}
 async function addAlias(){const slug=prompt('Nuevo alias');if(!slug)return;const res=await fetch('/api/aliases',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({slug})});const j=await res.json();if(res.ok)setAliases(x=>[...x,j]);else setMsg(j.error||'No se pudo crear');}
 async function delAlias(id:string){await fetch('/api/aliases',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({id})});setAliases(x=>x.filter(v=>v.id!==id));}
 function move(i:number,d:number){const n=[...links];const j=i+d;if(j<0||j>=n.length)return;[n[i],n[j]]=[n[j],n[i]];saveLinks(n)}
 async function addWidget(){const title=prompt('Título del widget');const url=prompt('URL');if(!title||!url)return;patch('widgets',[...widgets,{title,url,subtitle:''}]);}
 function delWidget(i:number){patch('widgets',widgets.filter((_:any,n:number)=>n!==i))}
 async function hostUpload(file:File){const f=new FormData();f.append('file',file);const res=await fetch('/api/host/upload',{method:'POST',body:f});const j=await res.json();if(res.ok)setHosted(x=>[j,...x]);else setMsg(j.error||'Error');}
 async function createPaste(){const title=prompt('Título');const content=prompt('Contenido');if(!content)return;const res=await fetch('/api/host/paste',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title,content})});const j=await res.json();if(res.ok)setHosted(x=>[j,...x]);else setMsg(j.error||'Error');}
 async function logout(){await fetch('/api/auth/logout',{method:'POST'});r.push('/');r.refresh()}
 return <div className="dash">
  <aside className="sidebar"><div className="account"><strong>{data.username}</strong><span>{data.email}</span></div><nav>{tabs.map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</nav><div className="sideFoot"><a href={`/${data.username}`} target="_blank">Ver perfil <ExternalLink size={15}/></a><button onClick={logout}>Salir <LogOut size={15}/></button></div></aside>
  <main className="dashMain"><header><div><h1>{tab}</h1><p>Configura tu perfil y guarda los cambios.</p></div>{!['Enlaces','Aliases','Host','Estadísticas'].includes(tab)&&<button className="btn primary" onClick={save} disabled={busy}><Save size={16}/>{busy?'Guardando…':'Guardar'}</button>}</header>{msg&&<div className="notice">{msg}</div>}
  {tab==='Perfil'&&<section className="panel grid2"><Field label="Nombre visible"><input value={p.displayName} onChange={e=>patch('displayName',e.target.value)}/></Field><Field label="Ubicación"><input value={p.location} onChange={e=>patch('location',e.target.value)}/></Field><Field label="Biografía"><textarea rows={5} value={p.bio} onChange={e=>patch('bio',e.target.value)}/></Field><Field label="Layout"><select value={p.layout} onChange={e=>patch('layout',e.target.value)}>{layouts.map(x=><option key={x}>{x}</option>)}</select></Field><Toggle label="Ocultar visitas" value={p.hideViews} onChange={v=>patch('hideViews',v)}/><Toggle label="Ocultar badges" value={p.hideBadges} onChange={v=>patch('hideBadges',v)}/><Field label="Color de badges"><input type="color" value={p.badgeColor} onChange={e=>patch('badgeColor',e.target.value)}/></Field></section>}
  {tab==='Medios'&&<section className="panel grid2">
    {([['Avatar','avatarUrl','image/*'],['Banner','bannerUrl','image/*'],['Fondo','backgroundUrl','image/*,video/*'],['Audio','audioUrl','audio/*'],['Cursor','cursorUrl','image/*'],['Fuente personalizada','fontUrl','.woff,.woff2']] as const).map(([label,key,accept])=><div className="uploadBox" key={key}><strong>{label}</strong><code>{p[key]||'Sin archivo'}</code><label className="btn"><Upload size={15}/>Subir<input hidden type="file" accept={accept} onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],key)}/></label></div>)}
    <Field label="Tipo de fondo"><select value={p.backgroundType} onChange={e=>patch('backgroundType',e.target.value)}><option value="color">Color</option><option value="image">Imagen</option><option value="video">Video</option></select></Field><Field label="Familia de fuente"><input value={p.fontFamily} onChange={e=>patch('fontFamily',e.target.value)}/></Field><Field label="Volumen"><input type="range" min="0" max="1" step="0.01" value={p.volume} onChange={e=>patch('volume',Number(e.target.value))}/></Field><Toggle label="Control de volumen" value={p.volumeControl} onChange={v=>patch('volumeControl',v)}/>
  </section>}
  {tab==='Apariencia'&&<section className="panel grid3">{[['Acento','accentColor'],['Fondo','backgroundColor'],['Texto','textColor'],['Iconos','iconColor'],['Secundario','secondaryColor'],['Borde','borderColor'],['Glow','glowColor']] .map(([l,k])=><Field key={k} label={l}><input type="color" value={p[k]} onChange={e=>patch(k,e.target.value)}/></Field>)}<Field label="Opacidad"><input type="range" min="0.15" max="1" step="0.01" value={p.profileOpacity} onChange={e=>patch('profileOpacity',Number(e.target.value))}/></Field><Field label="Blur"><input type="range" min="0" max="50" value={p.profileBlur} onChange={e=>patch('profileBlur',Number(e.target.value))}/></Field><Field label="Ancho de borde"><input type="number" min="0" max="12" value={p.borderWidth} onChange={e=>patch('borderWidth',Number(e.target.value))}/></Field><Field label="Radio del perfil"><input type="range" min="0" max="48" value={p.borderRadius} onChange={e=>patch('borderRadius',Number(e.target.value))}/></Field><Field label="Radio avatar"><input type="range" min="0" max="50" value={p.avatarRadius} onChange={e=>patch('avatarRadius',Number(e.target.value))}/></Field><Field label="Radio banner"><input type="range" min="0" max="40" value={p.bannerRadius} onChange={e=>patch('bannerRadius',Number(e.target.value))}/></Field><Field label="Fuerza glow"><input type="range" min="0" max="80" value={p.glowStrength} onChange={e=>patch('glowStrength',Number(e.target.value))}/></Field><Toggle label="Glow" value={p.glowEnabled} onChange={v=>patch('glowEnabled',v)}/><Toggle label="Gradiente" value={p.gradientEnabled} onChange={v=>patch('gradientEnabled',v)}/><Toggle label="Iconos monocromos" value={p.monochromeIcons} onChange={v=>patch('monochromeIcons',v)}/><Toggle label="Intercambiar colores" value={p.swapBoxColors} onChange={v=>patch('swapBoxColors',v)}/></section>}
  {tab==='Efectos'&&<section className="panel grid2"><Field label="Efecto de fondo"><select value={p.backgroundEffect} onChange={e=>patch('backgroundEffect',e.target.value)}>{bgEffects.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Efecto de usuario"><select value={p.usernameEffect} onChange={e=>patch('usernameEffect',e.target.value)}>{nameEffects.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Efecto de cursor"><select value={p.cursorEffect} onChange={e=>patch('cursorEffect',e.target.value)}>{cursorEffects.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Animación del perfil"><select value={p.profileAnimation} onChange={e=>patch('profileAnimation',e.target.value)}>{profileAnimations.map(x=><option key={x}>{x}</option>)}</select></Field><Toggle label="Título animado" value={p.animatedTitle} onChange={v=>patch('animatedTitle',v)}/><Toggle label="Máquina de escribir" value={p.typewriterEnabled} onChange={v=>patch('typewriterEnabled',v)}/><Field label="Textos de máquina de escribir"><textarea rows={7} value={typewriterText} onChange={e=>patch('typewriterTexts',e.target.value.split('\n').filter(Boolean))}/></Field><Field label="Velocidad escritura (ms)"><input type="number" min="10" max="500" value={p.typewriterSpeed} onChange={e=>patch('typewriterSpeed',Number(e.target.value))}/></Field><Field label="Velocidad borrado (ms)"><input type="number" min="10" max="500" value={p.typewriterDeleteSpeed} onChange={e=>patch('typewriterDeleteSpeed',Number(e.target.value))}/></Field></section>}
  {tab==='Enlaces'&&<section className="panel"><div className="panelTop"><span>{links.length} enlaces</span><button className="btn primary" onClick={addLink}><Plus size={15}/>Añadir</button></div><div className="list">{links.map((x,i)=><div className="listItem" key={x.id}><div className="grow"><input value={x.label} onChange={e=>setLinks(a=>a.map(v=>v.id===x.id?{...v,label:e.target.value}:v))}/><input value={x.url} onChange={e=>setLinks(a=>a.map(v=>v.id===x.id?{...v,url:e.target.value}:v))}/></div><label className="miniCheck"><input type="checkbox" checked={x.visible} onChange={e=>{const n=links.map(v=>v.id===x.id?{...v,visible:e.target.checked}:v);saveLinks(n)}}/> visible</label><button className="iconBtn" onClick={()=>move(i,-1)}><ArrowUp/></button><button className="iconBtn" onClick={()=>move(i,1)}><ArrowDown/></button><button className="iconBtn danger" onClick={()=>delLink(x.id)}><Trash2/></button></div>)}</div>{links.length>0&&<button className="btn primary" onClick={()=>saveLinks()}>Guardar enlaces</button>}</section>}
  {tab==='Widgets'&&<section className="panel"><div className="panelTop"><span>Disponibles en layout MODERN</span><button className="btn primary" onClick={addWidget}><Plus size={15}/>Añadir</button></div><div className="list">{widgets.map((w:any,i:number)=><div className="listItem" key={i}><div className="grow"><input value={w.title||''} onChange={e=>patch('widgets',widgets.map((v:any,n:number)=>n===i?{...v,title:e.target.value}:v))}/><input value={w.url||''} onChange={e=>patch('widgets',widgets.map((v:any,n:number)=>n===i?{...v,url:e.target.value}:v))}/><input value={w.subtitle||''} placeholder="Subtítulo" onChange={e=>patch('widgets',widgets.map((v:any,n:number)=>n===i?{...v,subtitle:e.target.value}:v))}/></div><button className="iconBtn danger" onClick={()=>delWidget(i)}><Trash2/></button></div>)}</div></section>}
  {tab==='SEO'&&<section className="panel grid2"><Field label="Título SEO"><input value={p.seoTitle} onChange={e=>patch('seoTitle',e.target.value)}/></Field><Field label="Descripción SEO"><textarea rows={5} value={p.seoDescription} onChange={e=>patch('seoDescription',e.target.value)}/></Field><Field label="Imagen embed"><input value={p.seoImage} onChange={e=>patch('seoImage',e.target.value)}/></Field><Field label="Favicon"><input value={p.faviconUrl} onChange={e=>patch('faviconUrl',e.target.value)}/></Field></section>}
  {tab==='Aliases'&&<section className="panel"><div className="panelTop"><span>URLs adicionales que redirigen a tu perfil</span><button className="btn primary" onClick={addAlias}><Plus size={15}/>Crear alias</button></div><div className="list">{aliases.map(a=><div className="listItem" key={a.id}><code>/{a.slug}</code><button className="iconBtn danger" onClick={()=>delAlias(a.id)}><Trash2/></button></div>)}</div></section>}
  {tab==='Host'&&<section className="panel"><div className="panelTop"><span>Imágenes, videos y textos alojados</span><div className="row gap"><label className="btn primary"><Upload size={15}/>Subir<input hidden type="file" accept="image/*,video/*" onChange={e=>e.target.files?.[0]&&hostUpload(e.target.files[0])}/></label><button className="btn" onClick={createPaste}><Plus size={15}/>Texto</button></div></div><div className="assetGrid">{hosted.map(a=><div className="asset" key={a.id}>{a.type==='IMAGE'&&<img src={a.url} alt=""/>}{a.type==='VIDEO'&&<video src={a.url}/>}<div><strong>{a.title||a.type}</strong><code>/h/{a.slug}</code><button className="iconBtn" onClick={()=>navigator.clipboard.writeText(`${location.origin}/h/${a.slug}`)}><Copy/></button></div></div>)}</div></section>}
  {tab==='Estadísticas'&&<><section className="stats"><div><span>Visitas</span><strong>{data._count.views.toLocaleString()}</strong></div><div><span>Visitantes únicos</span><strong>{data.analytics.uniqueViews.toLocaleString()}</strong></div><div><span>Clics</span><strong>{data._count.clicks.toLocaleString()}</strong></div><div><span>CTR</span><strong>{data._count.views?((data._count.clicks/data._count.views)*100).toFixed(1):'0.0'}%</strong></div></section>{data.analytics.topLinks.length>0&&<section className="panel analyticsPanel"><h2>Enlaces con más clics</h2>{data.analytics.topLinks.map((x:any,i:number)=><div className="metricRow" key={i}><span>{x.label}</span><strong>{x.clicks.toLocaleString()}</strong></div>)}</section>}</>}
  {tab==='Avanzado'&&<section className="panel grid2"><div className="discordConnect"><strong>Discord</strong><span>{p.discordId?'Cuenta conectada':'Sin conectar'}</span><a className="btn" href="/api/discord/connect">{p.discordId?'Reconectar':'Conectar Discord'}</a></div><Field label="Discord ID"><input value={p.discordId} readOnly/></Field><Field label="Avatar de Discord (URL)"><input value={p.discordAvatarUrl} readOnly/></Field><Toggle label="Mostrar tarjeta de Discord" value={p.discordPresence} onChange={v=>patch('discordPresence',v)}/><Toggle label="Decoración de avatar de Discord" value={p.discordDecoration} onChange={v=>patch('discordDecoration',v)}/><Field label="CSS personalizado"><textarea className="codeArea" rows={18} value={p.customCss} onChange={e=>patch('customCss',e.target.value)}/></Field></section>}
  </main>
 </div>
}
